import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./src/**/*.{js,ts,jsx,tsx}", // nếu anh có thư mục src
  ],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#e3d7db",
        primary: "#8a486f",
        "on-tertiary-fixed": "#072100",
        "tertiary-container": "#a0cd85",
        "surface-container-high": "#f2e5e9",
        "secondary-container": "#a6f2cf",
        "on-surface-variant": "#514349",
        surface: "#fff8f8",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-variant": "#ecdfe3",
        background: "#fff8f8",
        "primary-fixed": "#ffd8ea",
        "inverse-primary": "#ffaeda",
        "primary-fixed-dim": "#ffaeda",
        secondary: "#1b6b4f",
        "on-background": "#201a1d",
        "on-secondary-fixed-variant": "#00513a",
        "on-tertiary-container": "#31581d",
        "inverse-surface": "#352f31",
        "on-tertiary-fixed-variant": "#2a5016",
        "outline-variant": "#d5c1c9",
        "surface-container": "#f7ebee",
        "secondary-fixed-dim": "#8bd6b4",
        error: "#ba1a1a",
        "tertiary-fixed-dim": "#a6d38b",
        "on-primary": "#ffffff",
        "secondary-fixed": "#a6f2cf",
        "on-primary-fixed": "#3a0329",
        "on-secondary-container": "#247155",
        "inverse-on-surface": "#faeef1",
        "on-primary-fixed-variant": "#6f3157",
        "on-error": "#ffffff",
        "on-surface": "#201a1d",
        "surface-container-low": "#fdf0f4",
        "surface-container-highest": "#ecdfe3",
        "surface-tint": "#8a486f",
        "surface-bright": "#fff8f8",
        "on-secondary": "#ffffff",
        "on-primary-container": "#78395f",
        "tertiary-fixed": "#c1f0a4",
        "error-container": "#ffdad6",
        outline: "#83737a",
        "on-secondary-fixed": "#002115",
        "primary-container": "#f9a8d4",
        tertiary: "#41682c",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        gutter: "24px",
        "touch-target-min": "48px",
        sm: "12px",
        lg: "40px",
        md: "24px",
        base: "8px",
        xl: "64px",
      },
      fontFamily: {
        "headline-lg": ["Quicksand", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Quicksand", "sans-serif"],
        "headline-md": ["Quicksand", "sans-serif"],
        "price-display": ["Quicksand", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "label-lg": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "price-display": ["28px", { lineHeight: "32px", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

export default config;
