@baseUrl = http://localhost:3000
@token = {{login.response.body.data.token}}



### =========================
### đăng nhập
### =========================
# @name login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123"
}

### ========================================
### CREATE PRODUCT
### ========================================

POST {{baseUrl}}/api/products
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "name": "Latte đá viên",
  "category": "2",
  "sku": "Latte_dv",
  "price": "10000",
  "costPrice": "10000",
  "description": "Ngon lành cành đào",
  "active": true,
  "image": "/uploads/products/1779865812089-VTV-WC 1.png",
  "toppings": [
    {
      "id": null,
      "name": "Trân hoàng kim",
      "price": 5000
    },
    {
      "id": 1,
      "name": "Trân châu trắng",
      "image": "/uploads/toppings/tran-chau-trang.png",
      "price": 5000,
      "stock": 100,
      "status": "ACTIVE"
    }
  ]
}

### ========================================
### GET PRODUCTS
### ========================================

GET {{baseUrl}}/api/products
Authorization: Bearer {{token}}

### ========================================
### GET PRODUCTS WITH KEYWORD
### ========================================

GET {{baseUrl}}/products?keyword=kem
Authorization: Bearer {{token}}

### ========================================
### GET PRODUCTS BY CATEGORY
### ========================================

GET {{baseUrl}}/products?categoryId=1
Authorization: Bearer {{token}}

### ========================================
### GET PRODUCT DETAIL
### ========================================

GET {{baseUrl}}/api/products/1
Authorization: Bearer {{token}}

### ========================================
### UPDATE PRODUCT
### ========================================

PUT {{baseUrl}}/products/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Latte đá viên",
  "category": "2",
  "sku": "Latte_dv",
  "price": "10000",
  "costPrice": "10000",
  "description": "Ngon lành cành đào",
  "active": true,
  "image": "/uploads/products/1779865812089-VTV-WC 1.png",
  "toppings": [
    {
      "id": null,
      "name": "Trân hoàng kim",
      "price": 5000
    },
    {
      "id": 1,
      "name": "Trân châu trắng",
      "image": "/uploads/toppings/tran-chau-trang.png",
      "price": 5000,
      "stock": 100,
      "status": "ACTIVE"
    }
  ]
}

### ========================================
### DELETE PRODUCT
### ========================================

DELETE {{baseUrl}}/products/1
Authorization: Bearer {{token}}