import type { Metadata } from "next";
import { Toaster } from "sonner";
import "./globals.css";
import "./css2.css";
import "./css22.css";
import { Quicksand, Inter } from "next/font/google";
import { UserProvider } from "@/contexts/UserContext";

const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-quicksand",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${quicksand.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="font-body-md text-on-surface min-h-screen flex items-center justify-center relative">
        <div className="decorative-shape float-animation bg-secondary-fixed w-64 h-64 rounded-full -top-20 -left-20"></div>
        <div className="decorative-shape float-animation bg-primary-container w-80 h-80 rounded-full -bottom-32 -right-20"></div>
        <div className="decorative-shape float-animation bg-tertiary-fixed w-48 h-48 rounded-full top-1/4 -right-10"></div>
        <UserProvider>{children}</UserProvider>
        <Toaster />
        {/* <!-- Version Stamp --> */}
        <div className="fixed bottom-gutter left-gutter">
          <p className="font-label-md text-label-md text-on-surface-variant/40">
            v2.4.0-stable
          </p>
        </div>
      </body>
    </html>
  );
}
